# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6edb5f79bd2e9df2e040144447caffaec9ee00157947f14b1c6a700ff25385314b720f3866c24a277de80ac72586a8e5519ed6a44f2ec15d34e05cee520b4b7

test:
  secret_key_base: 019f054e193623c249f2b5e6192db95867023ebd76bf66d777e88c074438986a21e05af9bd564821cee99e63b19f8341bc935d561630e48b2ff804948d451fb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
